#!/bin/sh
uci set wireless.radio2.band='6g'
uci set wireless.radio2.country='US'
uci set wireless.radio2.channel='33'
uci set wireless.radio2.htmode='EHT320'
uci set wireless.radio2.cell_density='0'
uci set wireless.radio2.disabled='0'
uci commit wireless
wifi reload
sleep 6
iwinfo phy0.2-ap0 info | grep -E "Channel|Tx-Power|HT Mode|ESSID"
